### ISSUE TITLE
有关prompt

### ISSUE THREAD

**Issue by chenxi1228** [IronSpiderMan/MachineLearningPractice#3]
请问一下，

QA_CHAIN_PROMPT = PromptTemplate.from_template("""根据下面的上下文（context）内容回答问题。
如果你不知道答案，就回答不知道，不要试图编造答案。
答案最多3句话，保持答案简介。
总是在答案结束时说”谢谢你的提问！“
{context}
问题：{question}
""")

这个prompt是如何作用的？好像没看到相关的调用

**Comment by IronSpiderMan** [comment]
> 请问一下，
> 
> 
> 
> QA_CHAIN_PROMPT = PromptTemplate.from_template("""根据下面的上下文（context）内容回答问题。
> 
> 如果你不知道答案，就回答不知道，不要试图编造答案。
> 
> 答案最多3句话，保持答案简介。
> 
> 总是在答案结束时说”谢谢你的提问！“
> 
> {context}
> 
> 问题：{question}
> 
> """)
> 
> 
> 
> 这个prompt是如何作用的？好像没看到相关的调用

这个是langchain自动调用的，在创建qa的时候传入的参数kwargs替换了langchain默认的prompt模板

**Comment by chenxi1228** [comment]
> > 请问一下，
> > QA_CHAIN_PROMPT = PromptTemplate.from_template("""根据下面的上下文（context）内容回答问题。
> > 如果你不知道答案，就回答不知道，不要试图编造答案。
> > 答案最多3句话，保持答案简介。
> > 总是在答案结束时说”谢谢你的提问！“
> > {context}
> > 问题：{question}
> > """)
> > 这个prompt是如何作用的？好像没看到相关的调用
> 
> 这个是langchain自动调用的，在创建qa的时候传入的参数kwargs替换了langchain默认的prompt模板

了解了，感谢解答，谢谢！
